### ISSUE TITLE
If you are unable to connect after the max reconnect tries, you don't get kicked from the proxy.

### ISSUE THREAD

**Issue by mibby** [AoElite/AutoReconnect#5]
Would it be possible to add an option to kick players from BungeeCord with a client kick message if they are unable to reconnect to a server after the max reconnect tries / time?

Currently if the time runs out, they sit in the proxy void with the single loaded local client cached chunk area with a standard red java error connection message that shows up in chat. It would be better to kick players from the proxy and give them an actual disconnect message if they can't reconnect after the max tries and max time. Ideally you would always be able to reconnect to the server if it's restarting, but something may go wrong such as longer than usual update times or server crashes.

**Comment by PseudoResonance** [comment]
I have fixed this in my build of the plugin, available here. This feature is configurable, however, so make sure you set `do-not-disconnect` to false in the config, so that the player is disconnected if they cannot reconnect. This build also supports 1.16.
[AutoReconnect-1.4.jar.zip](https://github.com/AoElite/AutoReconnect/files/4827956/AutoReconnect-1.4.jar.zip)

**Comment by PseudoResonance** [comment]
No reply, so assuming issue is resolved.

**Comment by mibby** [comment]
Apologies, yes this seems to be fixed. Thank you!
